const path = require("path");
const tjs = require("typescript-json-schema");
const fs = require("fs");

const settings = {
  required: true,
  ref: false,
};

const compilerOptions = {
  strictNullChecks: true,
  esModuleInterop: true,
  skipLibCheck: true
};
const entitiesDir = path.resolve('src/entities');


const getEntityFiles = (dir) => {
  return fs.readdirSync(dir)
    .filter(file => file.endsWith('.entity.ts'))
    .map(file => path.join(dir, file));
};
const entityFiles = getEntityFiles(entitiesDir);


const program = tjs.getProgramFromFiles(
  entityFiles,
  compilerOptions,
  './',
);

const schema = tjs.generateSchema(program, "*", settings);


// Ensure the build directory exists
const buildDir = path.resolve(__dirname, "../build");

fs.writeFileSync(
  path.join(buildDir, "_schema.ts"),
  "// THIS FILE IS AUTO-GENERATED BY SCHEMAGENERATOR.JS\n" +
  "export const _schema = " + JSON.stringify(schema, null, 4) + ";"
);

console.log("Schema generated successfully");
